[theme]
primaryColor = "#b1b5b9"          # Azul — botões e destaques
backgroundColor = "#ffffff"       # Fundo principal branco
secondaryBackgroundColor = "#efefef" # Lateral azul escura
textColor = "#000000"             # Cor do texto
font = "sans serif"
